import type { LongCase } from "@/types/osce/longCase";

// Please take a focused history, perform an appropriate examination, and be ready to discuss the case afterwards.
export const cards: readonly LongCase[] = [
  {
    id: "1",
    title: "Breast lump",
    specialty: "Medicine",
    category: "Breast",
    difficulty: "Final MBBS",
    description: "A 45-year-old female has presented with a breast lump.",
    time_limit_seconds: 600,
    is_active: true,
    createdAt: "2023-01-01T00:00:00Z",
    updatedAt: "2023-01-01T00:00:00Z",
  },
  {
    id: "2",
    title: "Shortness of breath",
    specialty: "Medicine",
    category: "Respiratory",
    difficulty: "Final MBBS",
    description: "A 65-year-old male has presented with shortness of breath.",
    time_limit_seconds: 600,
    is_active: true,
    createdAt: "2023-01-01T00:00:00Z",
    updatedAt: "2023-01-01T00:00:00Z",
  },
  {
    id: "3",
    title: "Joint pain",
    specialty: "Paediatrics",
    category: "Musculoskeletal",
    difficulty: "Final MBBS",
    description: "A 10-year-old child has presented with joint pain.",
    time_limit_seconds: 600,
    is_active: true,
    createdAt: "2023-01-01T00:00:00Z",
    updatedAt: "2023-01-01T00:00:00Z",
  },
  {
    id: "4",
    title: "Appendicitis",
    specialty: "Surgery",
    category: "Gastrointestinal",
    difficulty: "Final MBBS",
    description: "A 25-year-old male has presented with appendicitis.",
    time_limit_seconds: 600,
    is_active: true,
    createdAt: "2023-01-01T00:00:00Z",
    updatedAt: "2023-01-01T00:00:00Z",
  },
  {
    id: "5",
    title: "Pregnancy complications",
    category: "Obstretics",
    specialty: "GynObs",
    difficulty: "Final MBBS",
    description: "A 30-year-old woman has presented with pregnancy complications.",
    time_limit_seconds: 600,
    is_active: true,
    createdAt: "2023-01-01T00:00:00Z",
    updatedAt: "2023-01-01T00:00:00Z",
  },
];
