// AUTO-GENERATED by scripts/generate-enum-consts.mjs — do not edit by hand.
// Regenerate with `npm run api:types` after any backend schema change.
// Source: the same openapi.json used to generate api-schema.d.ts, so these
// values and that file's types can't drift from each other.

export const ATTEMPT_STATUS = ["in_progress_history", "history_complete", "in_progress_examination", "examination_complete", "summary_complete", "evaluated"] as const;
export const DIFFICULTY_LEVEL = ["final_mbbs", "post_graduate"] as const;
export const EVALUATION_METHOD = ["string_match", "llm_judge"] as const;
export const EXAMINATION_NAME = ["general_examination", "systemic_examination"] as const;
export const HISTORY_ITEM_CATEGORY = ["presenting_complaint", "history_of_presenting_complaint", "past_medical_history", "past_surgical_history", "medication_history", "allergy_history", "family_history", "social_history", "antinatal_history", "birth_history", "developmental_history", "nutrition_history", "vaccination_history", "past_gynaecological_history", "past_obstetric_history", "past_menstrual_history"] as const;
export const INVESTIGATION_NAME = ["full_blood_count", "x_ray", "ct_scan"] as const;
export const LONG_CASE_CATEGORY = ["acute_fever", "prolonged_fever_PUO", "diabetes_mellitus", "hypertension", "chest_pain", "shortness_of_breath", "fever_with_respiratory_symptoms_RTI", "chronic_cough_and_hemoptysis", "swelling_of_the_body_edema", "jaundice", "CLCD", "joint_pain", "bleeding_disorders", "chronic_kidney_disease", "lower_limb_weakness", "hemiparesis", "connective_tissue_disease", "anemia", "stroke", "chronic_diarrhea", "thyroid_disorders", "breast_carcinoma", "upper_gastroenterology", "hepatopancreatobiliary", "colorectal", "vascular", "urology", "depression", "anxiety_disorders", "psychosis", "bipolar_disorder", "substance_use_disorders", "neonatal_disorders", "infectious_diseases", "respiratory_disorders", "gastrointestinal_disorders", "neurological_disorders", "obstetric_complications", "gynecological_disorders", "reproductive_health_issues"] as const;
export const MESSAGE_SENDER = ["student", "patient"] as const;
export const SPECIALTY = ["medicine", "surgery", "paediatrics", "gynobs", "psychiatry"] as const;
