/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/long-cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Long Cases */
        get: operations["list_long_cases_api_v1_long_cases_get"];
        put?: never;
        /** Create Long Case */
        post: operations["create_long_case_api_v1_long_cases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/long-cases/full": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Long Case With Details
         * @description Creates a long case together with its patient profile, history, examinations,
         *     investigations and differential diagnoses in one transaction.
         */
        post: operations["create_long_case_with_details_api_v1_long_cases_full_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/long-cases/{long_case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Long Case */
        get: operations["get_long_case_api_v1_long_cases__long_case_id__get"];
        put?: never;
        post?: never;
        /** Delete Long Case */
        delete: operations["delete_long_case_api_v1_long_cases__long_case_id__delete"];
        options?: never;
        head?: never;
        /** Update Long Case */
        patch: operations["update_long_case_api_v1_long_cases__long_case_id__patch"];
        trace?: never;
    };
    "/api/v1/long-cases/{long_case_id}/details": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Long Case Details */
        get: operations["get_long_case_details_api_v1_long_cases__long_case_id__details_get"];
        /**
         * Update Long Case With Details
         * @description Updates a long case and syncs all child collections in one transaction:
         *     children with an id are updated, without an id created, and omitted ones deleted.
         */
        put: operations["update_long_case_with_details_api_v1_long_cases__long_case_id__details_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/long-cases/{long_case_id}/patient-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Patient Profile */
        get: operations["get_patient_profile_api_v1_long_cases__long_case_id__patient_profile_get"];
        put?: never;
        /** Create Patient Profile */
        post: operations["create_patient_profile_api_v1_long_cases__long_case_id__patient_profile_post"];
        /** Delete Patient Profile */
        delete: operations["delete_patient_profile_api_v1_long_cases__long_case_id__patient_profile_delete"];
        options?: never;
        head?: never;
        /** Update Patient Profile */
        patch: operations["update_patient_profile_api_v1_long_cases__long_case_id__patient_profile_patch"];
        trace?: never;
    };
    "/api/v1/long-cases/{long_case_id}/history-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List History Items */
        get: operations["list_history_items_api_v1_long_cases__long_case_id__history_items_get"];
        put?: never;
        /** Create History Item */
        post: operations["create_history_item_api_v1_long_cases__long_case_id__history_items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/long-cases/{long_case_id}/history-items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get History Item */
        get: operations["get_history_item_api_v1_long_cases__long_case_id__history_items__item_id__get"];
        put?: never;
        post?: never;
        /** Delete History Item */
        delete: operations["delete_history_item_api_v1_long_cases__long_case_id__history_items__item_id__delete"];
        options?: never;
        head?: never;
        /** Update History Item */
        patch: operations["update_history_item_api_v1_long_cases__long_case_id__history_items__item_id__patch"];
        trace?: never;
    };
    "/api/v1/long-cases/{long_case_id}/examinations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Examinations */
        get: operations["list_examinations_api_v1_long_cases__long_case_id__examinations_get"];
        put?: never;
        /** Create Examination */
        post: operations["create_examination_api_v1_long_cases__long_case_id__examinations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/long-cases/{long_case_id}/examinations/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Examination */
        get: operations["get_examination_api_v1_long_cases__long_case_id__examinations__item_id__get"];
        put?: never;
        post?: never;
        /** Delete Examination */
        delete: operations["delete_examination_api_v1_long_cases__long_case_id__examinations__item_id__delete"];
        options?: never;
        head?: never;
        /** Update Examination */
        patch: operations["update_examination_api_v1_long_cases__long_case_id__examinations__item_id__patch"];
        trace?: never;
    };
    "/api/v1/long-cases/{long_case_id}/investigations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Investigations */
        get: operations["list_investigations_api_v1_long_cases__long_case_id__investigations_get"];
        put?: never;
        /** Create Investigation */
        post: operations["create_investigation_api_v1_long_cases__long_case_id__investigations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/long-cases/{long_case_id}/investigations/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Investigation */
        get: operations["get_investigation_api_v1_long_cases__long_case_id__investigations__item_id__get"];
        put?: never;
        post?: never;
        /** Delete Investigation */
        delete: operations["delete_investigation_api_v1_long_cases__long_case_id__investigations__item_id__delete"];
        options?: never;
        head?: never;
        /** Update Investigation */
        patch: operations["update_investigation_api_v1_long_cases__long_case_id__investigations__item_id__patch"];
        trace?: never;
    };
    "/api/v1/long-case-attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Attempts */
        get: operations["list_my_attempts_api_v1_long_case_attempts_get"];
        put?: never;
        /** Create Attempt */
        post: operations["create_attempt_api_v1_long_case_attempts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/long-case-attempts/{attempt_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Attempt */
        get: operations["get_attempt_api_v1_long_case_attempts__attempt_id__get"];
        put?: never;
        post?: never;
        /** Delete Attempt */
        delete: operations["delete_attempt_api_v1_long_case_attempts__attempt_id__delete"];
        options?: never;
        head?: never;
        /** Update Attempt */
        patch: operations["update_attempt_api_v1_long_case_attempts__attempt_id__patch"];
        trace?: never;
    };
    "/api/v1/long-case-attempts/{attempt_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Messages */
        get: operations["list_messages_api_v1_long_case_attempts__attempt_id__messages_get"];
        put?: never;
        /** Create Message */
        post: operations["create_message_api_v1_long_case_attempts__attempt_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/long-case-attempts/{attempt_id}/messages/{message_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Message */
        get: operations["get_message_api_v1_long_case_attempts__attempt_id__messages__message_id__get"];
        put?: never;
        post?: never;
        /** Delete Message */
        delete: operations["delete_message_api_v1_long_case_attempts__attempt_id__messages__message_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/long-case-attempts/{attempt_id}/examination-selections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Examination Selections */
        get: operations["list_examination_selections_api_v1_long_case_attempts__attempt_id__examination_selections_get"];
        put?: never;
        /** Create Examination Log */
        post: operations["create_examination_log_api_v1_long_case_attempts__attempt_id__examination_selections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/long-case-attempts/{attempt_id}/examination-selections/{log_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Examination Log */
        get: operations["get_examination_log_api_v1_long_case_attempts__attempt_id__examination_selections__log_id__get"];
        put?: never;
        post?: never;
        /** Delete Examination Log */
        delete: operations["delete_examination_log_api_v1_long_case_attempts__attempt_id__examination_selections__log_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/long-case-attempts/{attempt_id}/history-results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List History Results */
        get: operations["list_history_results_api_v1_long_case_attempts__attempt_id__history_results_get"];
        put?: never;
        /** Create History Result */
        post: operations["create_history_result_api_v1_long_case_attempts__attempt_id__history_results_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/long-case-attempts/{attempt_id}/history-results/{result_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get History Result */
        get: operations["get_history_result_api_v1_long_case_attempts__attempt_id__history_results__result_id__get"];
        put?: never;
        post?: never;
        /** Delete History Result */
        delete: operations["delete_history_result_api_v1_long_case_attempts__attempt_id__history_results__result_id__delete"];
        options?: never;
        head?: never;
        /** Update History Result */
        patch: operations["update_history_result_api_v1_long_case_attempts__attempt_id__history_results__result_id__patch"];
        trace?: never;
    };
    "/api/v1/long-case-attempts/{attempt_id}/messages/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Chat Message */
        post: operations["send_chat_message_api_v1_long_case_attempts__attempt_id__messages_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AttemptStatus
         * @enum {string}
         */
        AttemptStatus: "in_progress_history" | "history_complete" | "in_progress_examination" | "examination_complete" | "summary_complete" | "evaluated";
        /** DifferentialDiagnosisRead */
        DifferentialDiagnosisRead: {
            /** Diagnosis */
            diagnosis: string;
            /** Supporting Features */
            supporting_features?: string[];
            /**
             * Priority
             * @default 1
             */
            priority: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Long Case Id
             * Format: uuid
             */
            long_case_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** DifferentialDiagnosisWrite */
        DifferentialDiagnosisWrite: {
            /** Id */
            id?: string | null;
            /** Diagnosis */
            diagnosis: string;
            /** Supporting Features */
            supporting_features?: string[];
            /** Priority */
            priority: number;
        };
        /**
         * DifficultyLevel
         * @enum {string}
         */
        DifficultyLevel: "final_mbbs" | "post_graduate";
        /**
         * EvaluationMethod
         * @enum {string}
         */
        EvaluationMethod: "string_match" | "llm_judge";
        /**
         * ExaminationName
         * @enum {string}
         */
        ExaminationName: "general_examination" | "systemic_examination";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HistoryItemCategory
         * @enum {string}
         */
        HistoryItemCategory: "presenting_complaint" | "history_of_presenting_complaint" | "past medical_history" | "past surgical_history" | "medication_history" | "allergy_history" | "family_history" | "social_history" | "antinatal_history" | "birth_history" | "developmental_history" | "nutrition_history" | "vaccination_history" | "past_gynaecological_history" | "past_obstetric_history" | "past_menstrual_history";
        /** HistoryItemCreate */
        HistoryItemCreate: {
            category: components["schemas"]["HistoryItemCategory"];
            /** Description */
            description: string;
            /**
             * Points
             * @default 1
             */
            points: number;
        };
        /** HistoryItemRead */
        HistoryItemRead: {
            category: components["schemas"]["HistoryItemCategory"];
            /** Description */
            description: string;
            /**
             * Points
             * @default 1
             */
            points: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Long Case Id
             * Format: uuid
             */
            long_case_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** HistoryItemUpdate */
        HistoryItemUpdate: {
            category?: components["schemas"]["HistoryItemCategory"] | null;
            /** Description */
            description?: string | null;
            /** Points */
            points?: number | null;
        };
        /** HistoryItemWrite */
        HistoryItemWrite: {
            /** Id */
            id?: string | null;
            category: components["schemas"]["HistoryItemCategory"];
            /** Description */
            description: string;
            /**
             * Points
             * @default 1
             */
            points: number;
        };
        /**
         * InvestigationName
         * @enum {string}
         */
        InvestigationName: "full_blood_count" | "x_ray" | "ct_scan";
        /** LongCaseAttemptChatRequest */
        LongCaseAttemptChatRequest: {
            /** Content */
            content: string;
        };
        /** LongCaseAttemptChatResponse */
        LongCaseAttemptChatResponse: {
            user_message: components["schemas"]["LongCaseAttemptMessageRead"];
            assistant_message: components["schemas"]["LongCaseAttemptMessageRead"];
        };
        /** LongCaseAttemptCreate */
        LongCaseAttemptCreate: {
            /**
             * Long Case Id
             * Format: uuid
             */
            long_case_id: string;
        };
        /** LongCaseAttemptExaminationSelectionCreate */
        LongCaseAttemptExaminationSelectionCreate: {
            /** Query Text */
            query_text: string;
            /** Examination Id */
            examination_id?: string | null;
        };
        /** LongCaseAttemptExaminationSelectionRead */
        LongCaseAttemptExaminationSelectionRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Attempt Id
             * Format: uuid
             */
            attempt_id: string;
            /** Query Text */
            query_text: string;
            /** Examination Id */
            examination_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** LongCaseAttemptHistoryResultCreate */
        LongCaseAttemptHistoryResultCreate: {
            /**
             * History Item Id
             * Format: uuid
             */
            history_item_id: string;
            /** Is Met */
            is_met: boolean;
            /** Score Awarded */
            score_awarded: number;
            evaluation_method_used: components["schemas"]["EvaluationMethod"];
            /** Judge Reasoning */
            judge_reasoning?: string | null;
            /**
             * Evaluated At
             * Format: date-time
             */
            evaluated_at: string;
        };
        /** LongCaseAttemptHistoryResultRead */
        LongCaseAttemptHistoryResultRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Attempt Id
             * Format: uuid
             */
            attempt_id: string;
            /**
             * History Item Id
             * Format: uuid
             */
            history_item_id: string;
            /** Is Met */
            is_met: boolean;
            /** Score Awarded */
            score_awarded: number;
            evaluation_method_used: components["schemas"]["EvaluationMethod"];
            /** Judge Reasoning */
            judge_reasoning: string | null;
            /**
             * Evaluated At
             * Format: date-time
             */
            evaluated_at: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** LongCaseAttemptHistoryResultUpdate */
        LongCaseAttemptHistoryResultUpdate: {
            /** Is Met */
            is_met?: boolean | null;
            /** Score Awarded */
            score_awarded?: number | null;
            evaluation_method_used?: components["schemas"]["EvaluationMethod"] | null;
            /** Judge Reasoning */
            judge_reasoning?: string | null;
            /** Evaluated At */
            evaluated_at?: string | null;
        };
        /** LongCaseAttemptMessageCreate */
        LongCaseAttemptMessageCreate: {
            sender: components["schemas"]["MessageSender"];
            /** Content */
            content: string;
        };
        /** LongCaseAttemptMessageRead */
        LongCaseAttemptMessageRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Attempt Id
             * Format: uuid
             */
            attempt_id: string;
            sender: components["schemas"]["MessageSender"];
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** LongCaseAttemptRead */
        LongCaseAttemptRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Student Id
             * Format: uuid
             */
            student_id: string;
            /**
             * Long Case Id
             * Format: uuid
             */
            long_case_id: string;
            status: components["schemas"]["AttemptStatus"];
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** History Completed At */
            history_completed_at: string | null;
            /** Examination Completed At */
            examination_completed_at: string | null;
            /** Summary Completed At */
            summary_completed_at: string | null;
            /** Evaluated At */
            evaluated_at: string | null;
            /** Total Score */
            total_score: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * LongCaseAttemptUpdate
         * @description Progression/evaluation fields. student_id and long_case_id are immutable after creation.
         */
        LongCaseAttemptUpdate: {
            status?: components["schemas"]["AttemptStatus"] | null;
            /** History Completed At */
            history_completed_at?: string | null;
            /** Examination Completed At */
            examination_completed_at?: string | null;
            /** Summary Completed At */
            summary_completed_at?: string | null;
            /** Evaluated At */
            evaluated_at?: string | null;
            /** Total Score */
            total_score?: number | null;
        };
        /**
         * LongCaseCategory
         * @enum {string}
         */
        LongCaseCategory: "acute_fever" | "prolonged_fever_PUO" | "diabetes_mellitus" | "hypertension" | "chest_pain" | "shortness_of_breath" | "fever_with_respiratory_symptoms_RTI" | "chronic_cough_and_hemoptysis" | "swelling_of_the_body_edema" | "jaundice" | "CLCD" | "joint_pain" | "bleeding_disorders" | "chronic_kidney_disease" | "lower_limb_weakness" | "hemiparesis" | "connective_tissue_disease" | "anemia" | "stroke" | "chronic_diarrhea" | "thyroid_disorders" | "breast_carcinoma" | "upper_gastroenterology" | "hepatopancreatobiliary" | "colorectal" | "vascular" | "urology" | "depression" | "anxiety_disorders" | "psychosis" | "bipolar_disorder" | "substance_use_disorders" | "neonatal_disorders" | "infectious_diseases" | "respiratory_disorders" | "gastrointestinal_disorders" | "neurological_disorders" | "obstetric_complications" | "gynecological_disorders" | "reproductive_health_issues";
        /** LongCaseCreate */
        LongCaseCreate: {
            /** Title */
            title: string;
            specialty: components["schemas"]["Specialty"];
            category?: components["schemas"]["LongCaseCategory"] | null;
            /** @default final_mbbs */
            difficulty: components["schemas"]["DifficultyLevel"];
            /** Description */
            description?: string | null;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /** LongCaseDetail */
        LongCaseDetail: {
            /** Title */
            title: string;
            specialty: components["schemas"]["Specialty"];
            category?: components["schemas"]["LongCaseCategory"] | null;
            /** @default final_mbbs */
            difficulty: components["schemas"]["DifficultyLevel"];
            /** Description */
            description?: string | null;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            patient_profile?: components["schemas"]["PatientProfileRead"] | null;
            /** History Items */
            history_items?: components["schemas"]["HistoryItemRead"][];
            /** Examinations */
            examinations?: components["schemas"]["LongCaseExaminationRead"][];
            /** Investigations */
            investigations?: components["schemas"]["LongCaseInvestigationRead"][];
            /** Differential Diagnoses */
            differential_diagnoses?: components["schemas"]["DifferentialDiagnosisRead"][];
        };
        /** LongCaseExaminationCreate */
        LongCaseExaminationCreate: {
            name: components["schemas"]["ExaminationName"];
            /** Findings */
            findings: string;
            /**
             * Points
             * @default 1
             */
            points: number;
        };
        /** LongCaseExaminationRead */
        LongCaseExaminationRead: {
            name: components["schemas"]["ExaminationName"];
            /** Findings */
            findings: string;
            /**
             * Points
             * @default 1
             */
            points: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Long Case Id
             * Format: uuid
             */
            long_case_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** LongCaseExaminationUpdate */
        LongCaseExaminationUpdate: {
            name?: components["schemas"]["ExaminationName"] | null;
            /** Findings */
            findings?: string | null;
            /** Points */
            points?: number | null;
        };
        /** LongCaseExaminationWrite */
        LongCaseExaminationWrite: {
            /** Id */
            id?: string | null;
            name: components["schemas"]["ExaminationName"];
            /** Findings */
            findings: string;
            /**
             * Points
             * @default 1
             */
            points: number;
        };
        /** LongCaseInvestigationCreate */
        LongCaseInvestigationCreate: {
            name: components["schemas"]["InvestigationName"];
            /** Findings */
            findings: string;
            /**
             * Points
             * @default 1
             */
            points: number;
        };
        /** LongCaseInvestigationRead */
        LongCaseInvestigationRead: {
            name: components["schemas"]["InvestigationName"];
            /** Findings */
            findings: string;
            /**
             * Points
             * @default 1
             */
            points: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Long Case Id
             * Format: uuid
             */
            long_case_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** LongCaseInvestigationUpdate */
        LongCaseInvestigationUpdate: {
            name?: components["schemas"]["InvestigationName"] | null;
            /** Findings */
            findings?: string | null;
            /** Points */
            points?: number | null;
        };
        /** LongCaseInvestigationWrite */
        LongCaseInvestigationWrite: {
            /** Id */
            id?: string | null;
            name: components["schemas"]["InvestigationName"];
            /** Findings */
            findings: string;
            /**
             * Points
             * @default 1
             */
            points: number;
        };
        /** LongCaseRead */
        LongCaseRead: {
            /** Title */
            title: string;
            specialty: components["schemas"]["Specialty"];
            category?: components["schemas"]["LongCaseCategory"] | null;
            /** @default final_mbbs */
            difficulty: components["schemas"]["DifficultyLevel"];
            /** Description */
            description?: string | null;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** LongCaseUpdate */
        LongCaseUpdate: {
            /** Title */
            title?: string | null;
            specialty?: components["schemas"]["Specialty"] | null;
            category?: components["schemas"]["LongCaseCategory"] | null;
            difficulty?: components["schemas"]["DifficultyLevel"] | null;
            /** Description */
            description?: string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** LongCaseWrite */
        LongCaseWrite: {
            /** Title */
            title: string;
            specialty: components["schemas"]["Specialty"];
            category: components["schemas"]["LongCaseCategory"];
            /** @default final_mbbs */
            difficulty: components["schemas"]["DifficultyLevel"];
            /** Description */
            description?: string | null;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            patient_profile?: components["schemas"]["PatientProfileCreate"] | null;
            /** History Items */
            history_items?: components["schemas"]["HistoryItemWrite"][];
            /** Examinations */
            examinations?: components["schemas"]["LongCaseExaminationWrite"][];
            /** Investigations */
            investigations?: components["schemas"]["LongCaseInvestigationWrite"][];
            /** Differential Diagnoses */
            differential_diagnoses?: components["schemas"]["DifferentialDiagnosisWrite"][];
        };
        /**
         * MessageSender
         * @enum {string}
         */
        MessageSender: "student" | "patient";
        /** PatientProfileCreate */
        PatientProfileCreate: {
            /** Name */
            name?: string | null;
            /** Age */
            age?: number | null;
            /** Sex */
            sex?: string | null;
            /** Occupation */
            occupation?: string | null;
            /** Location */
            location?: string | null;
            /** Marital Status */
            marital_status?: string | null;
            /** Height Cm */
            height_cm?: number | null;
            /** Weight Kg */
            weight_kg?: number | null;
        };
        /** PatientProfileRead */
        PatientProfileRead: {
            /** Name */
            name?: string | null;
            /** Age */
            age?: number | null;
            /** Sex */
            sex?: string | null;
            /** Occupation */
            occupation?: string | null;
            /** Location */
            location?: string | null;
            /** Marital Status */
            marital_status?: string | null;
            /** Height Cm */
            height_cm?: number | null;
            /** Weight Kg */
            weight_kg?: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Long Case Id
             * Format: uuid
             */
            long_case_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** PatientProfileUpdate */
        PatientProfileUpdate: {
            /** Name */
            name?: string | null;
            /** Age */
            age?: number | null;
            /** Sex */
            sex?: string | null;
            /** Occupation */
            occupation?: string | null;
            /** Location */
            location?: string | null;
            /** Marital Status */
            marital_status?: string | null;
            /** Height Cm */
            height_cm?: number | null;
            /** Weight Kg */
            weight_kg?: number | null;
        };
        /**
         * Specialty
         * @enum {string}
         */
        Specialty: "medicine" | "surgery" | "paediatrics" | "gynobs" | "psychiatry";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_long_cases_api_v1_long_cases_get: {
        parameters: {
            query?: {
                specialty?: components["schemas"]["Specialty"] | null;
                is_active?: boolean | null;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LongCaseRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_long_case_api_v1_long_cases_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LongCaseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LongCaseRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_long_case_with_details_api_v1_long_cases_full_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LongCaseWrite"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LongCaseDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_long_case_api_v1_long_cases__long_case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                long_case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LongCaseRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_long_case_api_v1_long_cases__long_case_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                long_case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_long_case_api_v1_long_cases__long_case_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                long_case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LongCaseUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LongCaseRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_long_case_details_api_v1_long_cases__long_case_id__details_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                long_case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LongCaseDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_long_case_with_details_api_v1_long_cases__long_case_id__details_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                long_case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LongCaseWrite"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LongCaseDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_patient_profile_api_v1_long_cases__long_case_id__patient_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                long_case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientProfileRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_patient_profile_api_v1_long_cases__long_case_id__patient_profile_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                long_case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatientProfileCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientProfileRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_patient_profile_api_v1_long_cases__long_case_id__patient_profile_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                long_case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_patient_profile_api_v1_long_cases__long_case_id__patient_profile_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                long_case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatientProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientProfileRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_history_items_api_v1_long_cases__long_case_id__history_items_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                long_case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryItemRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_history_item_api_v1_long_cases__long_case_id__history_items_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                long_case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HistoryItemCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryItemRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_history_item_api_v1_long_cases__long_case_id__history_items__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                long_case_id: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryItemRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_history_item_api_v1_long_cases__long_case_id__history_items__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                long_case_id: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_history_item_api_v1_long_cases__long_case_id__history_items__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                long_case_id: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HistoryItemUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryItemRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_examinations_api_v1_long_cases__long_case_id__examinations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                long_case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LongCaseExaminationRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_examination_api_v1_long_cases__long_case_id__examinations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                long_case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LongCaseExaminationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LongCaseExaminationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_examination_api_v1_long_cases__long_case_id__examinations__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                long_case_id: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LongCaseExaminationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_examination_api_v1_long_cases__long_case_id__examinations__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                long_case_id: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_examination_api_v1_long_cases__long_case_id__examinations__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                long_case_id: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LongCaseExaminationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LongCaseExaminationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_investigations_api_v1_long_cases__long_case_id__investigations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                long_case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LongCaseInvestigationRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_investigation_api_v1_long_cases__long_case_id__investigations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                long_case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LongCaseInvestigationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LongCaseInvestigationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_investigation_api_v1_long_cases__long_case_id__investigations__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                long_case_id: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LongCaseInvestigationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_investigation_api_v1_long_cases__long_case_id__investigations__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                long_case_id: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_investigation_api_v1_long_cases__long_case_id__investigations__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                long_case_id: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LongCaseInvestigationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LongCaseInvestigationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_attempts_api_v1_long_case_attempts_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LongCaseAttemptRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_attempt_api_v1_long_case_attempts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LongCaseAttemptCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LongCaseAttemptRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_attempt_api_v1_long_case_attempts__attempt_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LongCaseAttemptRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_attempt_api_v1_long_case_attempts__attempt_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_attempt_api_v1_long_case_attempts__attempt_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LongCaseAttemptUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LongCaseAttemptRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_messages_api_v1_long_case_attempts__attempt_id__messages_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LongCaseAttemptMessageRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_message_api_v1_long_case_attempts__attempt_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LongCaseAttemptMessageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LongCaseAttemptMessageRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_message_api_v1_long_case_attempts__attempt_id__messages__message_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: string;
                message_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LongCaseAttemptMessageRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_message_api_v1_long_case_attempts__attempt_id__messages__message_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: string;
                message_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_examination_selections_api_v1_long_case_attempts__attempt_id__examination_selections_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LongCaseAttemptExaminationSelectionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_examination_log_api_v1_long_case_attempts__attempt_id__examination_selections_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LongCaseAttemptExaminationSelectionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LongCaseAttemptExaminationSelectionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_examination_log_api_v1_long_case_attempts__attempt_id__examination_selections__log_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: string;
                log_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LongCaseAttemptExaminationSelectionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_examination_log_api_v1_long_case_attempts__attempt_id__examination_selections__log_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: string;
                log_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_history_results_api_v1_long_case_attempts__attempt_id__history_results_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LongCaseAttemptHistoryResultRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_history_result_api_v1_long_case_attempts__attempt_id__history_results_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LongCaseAttemptHistoryResultCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LongCaseAttemptHistoryResultRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_history_result_api_v1_long_case_attempts__attempt_id__history_results__result_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: string;
                result_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LongCaseAttemptHistoryResultRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_history_result_api_v1_long_case_attempts__attempt_id__history_results__result_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: string;
                result_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_history_result_api_v1_long_case_attempts__attempt_id__history_results__result_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: string;
                result_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LongCaseAttemptHistoryResultUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LongCaseAttemptHistoryResultRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_chat_message_api_v1_long_case_attempts__attempt_id__messages_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LongCaseAttemptChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LongCaseAttemptChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
