"""initial schema

Revision ID: 9402862d137c
Revises: 
Create Date: 2026-09-23 11:56:11.983674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9402862d137c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('long_cases',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('specialty', sa.Enum('MEDICINE', 'SURGERY', 'PAEDIATRICS', 'GYNOBS', 'PSYCHIATRY', name='specialty'), nullable=False),
    sa.Column('category', sa.Enum('ACUTE_FEVER', 'PROLONGED_FEVER_PUO', 'DIABETES_MELLITUS', 'HYPERTENSION', 'CHEST_PAIN', 'SHORTNESS_OF_BREATH', 'FEVER_WITH_RESPIRATORY_SYMPTOMS_RTI', 'CHRONIC_COUGH_AND_HEMOPTYSIS', 'SWELLING_OF_THE_BODY_EDEMA', 'JAUNDICE', 'CLCD', 'JOINT_PAIN', 'BLEEDING_DISORDERS', 'CHRONIC_KIDNEY_DISEASE', 'LOWER_LIMB_WEAKNESS', 'HEMIPARESIS', 'CONNECTIVE_TISSUE_DISEASE', 'ANEMIA', 'STROKE', 'CHRONIC_DIARRHEA', 'THYROID_DISORDERS', 'BREAST_CARCINOMA', 'UPPER_GASTROENTEROLOGY', 'HEPATOPANCREATOBILIARY', 'COLORECTAL', 'VASCULAR', 'UROLOGY', 'DEPRESSION', 'ANXIETY_DISORDERS', 'PSYCHOSIS', 'BIPOLAR_DISORDER', 'SUBSTANCE_USE_DISORDERS', 'NEONATAL_DISORDERS', 'INFECTIOUS_DISEASES', 'RESPIRATORY_DISORDERS', 'GASTROINTESTINAL_DISORDERS', 'NEUROLOGICAL_DISORDERS', 'OBSTETRIC_COMPLICATIONS', 'GYNECOLOGICAL_DISORDERS', 'REPRODUCTIVE_HEALTH_ISSUES', name='longcasecategory'), nullable=True),
    sa.Column('difficulty', sa.Enum('EASY', 'MODERATE', 'HARD', name='difficultylevel'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('time_limit_seconds', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('differential_diagnoses', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('supporting_features', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_long_cases_specialty'), 'long_cases', ['specialty'], unique=False)
    op.create_table('users',
    sa.Column('clerk_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_clerk_id'), 'users', ['clerk_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_table('history_items',
    sa.Column('long_case_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('PC', 'HOPC', 'PMH', 'PSH', 'MEDICATION_HISTORY', 'ALLERGY_HISTORY', 'FAMILY_HISTORY', 'SOCIAL_HISTORY', 'ANTINATAL_HISTORY', 'BIRTH_HISTORY', 'DEVELOPMENTAL_HISTORY', 'NUTRITION_HISTORY', 'VACCINATION_HISTORY', 'PGH', 'POH', 'MENSTRUAL_HISTORY', name='historyitemcategory'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('is_critical', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['long_case_id'], ['long_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_items_category'), 'history_items', ['category'], unique=False)
    op.create_index(op.f('ix_history_items_long_case_id'), 'history_items', ['long_case_id'], unique=False)
    op.create_table('long_case_attempts',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('long_case_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS_HISTORY', 'HISTORY_COMPLETE', 'IN_PROGRESS_EXAMINATION', 'EXAMINATION_COMPLETE', 'SUMMARY_COMPLETE', 'EVALUATED', name='attemptstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('history_completed_at', sa.DateTime(), nullable=True),
    sa.Column('examination_completed_at', sa.DateTime(), nullable=True),
    sa.Column('summary_completed_at', sa.DateTime(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['long_case_id'], ['long_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'long_case_id', name='uq_student_long_case_attempt')
    )
    op.create_index(op.f('ix_long_case_attempts_long_case_id'), 'long_case_attempts', ['long_case_id'], unique=False)
    op.create_index(op.f('ix_long_case_attempts_status'), 'long_case_attempts', ['status'], unique=False)
    op.create_index(op.f('ix_long_case_attempts_student_id'), 'long_case_attempts', ['student_id'], unique=False)
    op.create_table('long_case_examinations',
    sa.Column('long_case_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Enum('GENERAL_EXAMINATION', 'SYSTEMIC_EXAMINATION', name='examinationname'), nullable=False),
    sa.Column('findings', sa.Text(), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['long_case_id'], ['long_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_long_case_examinations_long_case_id'), 'long_case_examinations', ['long_case_id'], unique=False)
    op.create_table('long_case_investigations',
    sa.Column('long_case_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Enum('FBC', 'XRAY', 'CT', name='investigationname'), nullable=False),
    sa.Column('findings', sa.Text(), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['long_case_id'], ['long_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_long_case_investigations_long_case_id'), 'long_case_investigations', ['long_case_id'], unique=False)
    op.create_table('patient_profiles',
    sa.Column('long_case_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(length=20), nullable=True),
    sa.Column('occupation', sa.String(length=150), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('marital_status', sa.String(length=50), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['long_case_id'], ['long_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('long_case_id', 'id', name='uq_case_patient_profile')
    )
    op.create_index(op.f('ix_patient_profiles_long_case_id'), 'patient_profiles', ['long_case_id'], unique=False)
    op.create_table('long_case_attempt_checklist_results',
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('history_item_id', sa.UUID(), nullable=False),
    sa.Column('is_met', sa.Boolean(), nullable=False),
    sa.Column('score_awarded', sa.Float(), nullable=False),
    sa.Column('evaluation_method_used', sa.Enum('STRING_MATCH', 'LLM_JUDGE', name='evaluationmethod'), nullable=False),
    sa.Column('judge_reasoning', sa.Text(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['long_case_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['history_item_id'], ['history_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'history_item_id', name='uq_attempt_checklist_item')
    )
    op.create_index(op.f('ix_long_case_attempt_checklist_results_attempt_id'), 'long_case_attempt_checklist_results', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_long_case_attempt_checklist_results_history_item_id'), 'long_case_attempt_checklist_results', ['history_item_id'], unique=False)
    op.create_table('long_case_attempt_examination_logs',
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('query_text', sa.String(length=255), nullable=False),
    sa.Column('examination_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['long_case_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['examination_id'], ['long_case_examinations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_long_case_attempt_examination_logs_attempt_id'), 'long_case_attempt_examination_logs', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_long_case_attempt_examination_logs_examination_id'), 'long_case_attempt_examination_logs', ['examination_id'], unique=False)
    op.create_table('long_case_attempt_messages',
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('sender', sa.Enum('STUDENT', 'PATIENT', name='messagesender'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['long_case_attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_long_case_attempt_messages_attempt_id'), 'long_case_attempt_messages', ['attempt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_long_case_attempt_messages_attempt_id'), table_name='long_case_attempt_messages')
    op.drop_table('long_case_attempt_messages')
    op.drop_index(op.f('ix_long_case_attempt_examination_logs_examination_id'), table_name='long_case_attempt_examination_logs')
    op.drop_index(op.f('ix_long_case_attempt_examination_logs_attempt_id'), table_name='long_case_attempt_examination_logs')
    op.drop_table('long_case_attempt_examination_logs')
    op.drop_index(op.f('ix_long_case_attempt_checklist_results_history_item_id'), table_name='long_case_attempt_checklist_results')
    op.drop_index(op.f('ix_long_case_attempt_checklist_results_attempt_id'), table_name='long_case_attempt_checklist_results')
    op.drop_table('long_case_attempt_checklist_results')
    op.drop_index(op.f('ix_patient_profiles_long_case_id'), table_name='patient_profiles')
    op.drop_table('patient_profiles')
    op.drop_index(op.f('ix_long_case_investigations_long_case_id'), table_name='long_case_investigations')
    op.drop_table('long_case_investigations')
    op.drop_index(op.f('ix_long_case_examinations_long_case_id'), table_name='long_case_examinations')
    op.drop_table('long_case_examinations')
    op.drop_index(op.f('ix_long_case_attempts_student_id'), table_name='long_case_attempts')
    op.drop_index(op.f('ix_long_case_attempts_status'), table_name='long_case_attempts')
    op.drop_index(op.f('ix_long_case_attempts_long_case_id'), table_name='long_case_attempts')
    op.drop_table('long_case_attempts')
    op.drop_index(op.f('ix_history_items_long_case_id'), table_name='history_items')
    op.drop_index(op.f('ix_history_items_category'), table_name='history_items')
    op.drop_table('history_items')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_clerk_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_long_cases_specialty'), table_name='long_cases')
    op.drop_table('long_cases')
    # ### end Alembic commands ###
